### ISSUE TITLE
Patience does not expire on same value of metric

### ISSUE THREAD

**Issue by Remorax** [naver/pasero#3]
On using WER as metric, I notice that the patience value does not decrement when average score equals best score. Ideally patience should only stop decrementing when the metric value improves over the best score.

 
![Screenshot 2024-02-04 at 12 59 04 am](https://github.com/naver/pasero/assets/26062692/42ef6ffb-1442-4ef8-88fe-61eab240531a)

**Comment by alex-berard** [comment]
Hi Vivek,
You can see [here](https://github.com/naver/pasero/blob/main/cli/train.py#L409) that the code already behaves as you suggest. What happened in your example is that WER actually decreased, but since the logs only show two digits, it appears like the score hasn't changed
